### ISSUE TITLE
Klee does not close Ollama upon shutdown

### ISSUE THREAD

**Issue by DaBomber60** [signerlabs/Klee#24]
## Issue
When closing Klee, it does not properly close Ollama, causing GPU memory to be filled with whatever model was loaded into memory.

## Details
Klee_1.5.0_Windows_Nvidia
Windows 11
i7-12700KF
RTX 4080
32GB RAM

**Comment by w-zhong** [comment]
fixed with version 1.5.1

**Comment by DaBomber60** [comment]
This issue persists in 1.5.1, Klee has been closed, but ollama.exe is still running and VRAM is filled.

![Image](https://github.com/user-attachments/assets/4281456e-a9a6-4c1f-ba6c-c0cddab6642c)

![Image](https://github.com/user-attachments/assets/0c06c06d-a896-420f-9433-8232f0aa9389)

**Comment by DaBomber60** [comment]
@w-zhong I am unable to reopen the issue, but don't wanna cause clutter with a new issue
